version: '3.4'

services:
  globoticket.web:
    image: ${DOCKER_REGISTRY-}globoticketweb
    build:
      context: .
      dockerfile: GloboTicket.Client/Dockerfile
    environment:
      - ApiConfigs__EventCatalog__Uri=http://globoticket.services.eventcatalog
      - ApiConfigs__ShoppingBasket__Uri=http://globoticket.services.shoppingbasket
    depends_on:
      - globoticket.services.eventcatalog
      - globoticket.services.shoppingbasket

  globoticket.services.eventcatalog:
    image: ${DOCKER_REGISTRY-}globoticketserviceseventcatalog
    build:
      context: .
      dockerfile: GloboTicket.Services.EventCatalog/Dockerfile

  globoticket.services.shoppingbasket:
    image: ${DOCKER_REGISTRY-}globoticketservicesshoppingbasket
    build:
      context: .
      dockerfile: GloboTicket.Services.ShoppingBasket/Dockerfile
    environment:
      - ApiConfigs__EventCatalog__Uri=http://globoticket.services.eventcatalog
    depends_on:
      - globoticket.services.eventcatalog
  
  external.paymentgateway:
    image: ${DOCKER_REGISTRY-}externalpaymentgateway
    build:
      context: .
      dockerfile: External.PaymentGateway/Dockerfile


  globoticket.web.bff:
    image: ${DOCKER_REGISTRY-}globoticketwebbff
    build:
      context: .
      dockerfile: GloboTicket.Web.Bff/Dockerfile


  globoticket.gateway.mobilebff:
    image: ${DOCKER_REGISTRY-}globoticketgatewaymobilebff
    build:
      context: .
      dockerfile: GloboTicket.Gateway.MobileBff/Dockerfile


  globoticket.gateway.webbff:
    image: ${DOCKER_REGISTRY-}globoticketgatewaywebbff
    build:
      context: .
      dockerfile: GloboTicket.Gateway.WebBff/Dockerfile


  globoticket.services.discount:
    image: ${DOCKER_REGISTRY-}globoticketservicesdiscount
    build:
      context: .
      dockerfile: GloboTicket.Services.Discount/Dockerfile


  globoticket.services.marketing:
    image: ${DOCKER_REGISTRY-}globoticketservicesmarketing
    build:
      context: .
      dockerfile: GloboTicket.Services.Marketing/Dockerfile
    environment:
      - ApiConfigs__ShoppingBasket__Uri=http://globoticket.services.shoppingbasket
    depends_on:
      - globoticket.services.shoppingbasket

  globoticket.services.ordering:
    image: ${DOCKER_REGISTRY-}globoticketservicesordering
    build:
      context: .
      dockerfile: GloboTicket.Services.Order/Dockerfile
  
  globoticket.services.payment:
    image: ${DOCKER_REGISTRY-}globoticketservicespayment
    build:
      context: .
      dockerfile: GloboTicket.Services.Payment/Dockerfile





